### ISSUE TITLE
您好，获取__jsl_clearance值这里不能用了

### ISSUE THREAD

**Issue by Aruelius** [einherjarcai/spider#1]
JS执行那段代码一直报错。

**Comment by einherjarcai** [comment]
@MikuShare 不好意思刚看到，这是js执行失败了，添加下面第二行代码就可以了

`js_final = js_final.replace("return return", "return eval")`
 ` js_final = re.sub(re.compile(r'document.*?toLowerCase\(\);', re.S), "'www.gsxt.gov.cn/';", js_final)`

**Comment by Aruelius** [comment]
刚刚试了一下，好像确实是OK了，但是偶尔还是会出问题，等有时间再测试一下。
